version: '3.3'

networks:
  ensimagcafet-network:
    name: EnsimagCafet-Network
    driver: bridge

volumes:
  postgres-data:
    name: EnsimagCafet-PostgresData-Volume
    driver: local
  antiforgery-keys-data:
    name: EnsimagCafet-AntiforgeryKeysData-Volume
    driver: local

services:
  ensimagcafet.web:
    container_name: EnsimagCafet.Web
    image: ${DOCKER_REGISTRY-}ensimagcafetweb
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.Web/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet-network
    volumes:
      - antiforgery-keys-data:/var/af-keys
    labels:
      - traefik.enable=true

      - traefik.http.routers.cafetensimagrouter.rule=Host(`cafet-ensimag.fr`)
      - traefik.http.routers.cafetensimagrouter.entrypoints=http
      - traefik.http.routers.cafetensimagrouter.service=ensimagcafetservice
      - traefik.http.routers.cafetensimagrouter.middlewares=redirecthttps

      - traefik.http.routers.cafetensimagroutersecure.rule=Host(`cafet-ensimag.fr`)
      - traefik.http.routers.cafetensimagroutersecure.entrypoints=https
      - traefik.http.routers.cafetensimagroutersecure.service=ensimagcafetservice
      - traefik.http.routers.cafetensimagroutersecure.tls=true
      - traefik.http.routers.cafetensimagroutersecure.tls.certresolver=dns-letsencrypt-resolver

      - traefik.http.services.ensimagcafetservice.loadbalancer.server.port=80

      - traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https
      - traefik.http.middlewares.redirecthttps.redirectscheme.permanent=true
  ensimagcafet.entityframeworkcore.dbmigrator:
    container_name: EnsimagCafet.EntityFrameworkCore.DbMigrator
    image: ${DOCKER_REGISTRY-}ensimagcafetentityframeworkcoredbmigrator
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.EntityFrameworkCore.DbMigrator/Dockerfile
    environment:
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet-network
  postgres:
    container_name: Postgres
    image: postgres
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: ensimagcafetdev
      POSTGRES_PASSWORD: EnsimagCafetDev
      POSTGRES_DB: ensimagcafetdev
    networks:
      - ensimagcafet-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
