version: '3.3'

networks:
  ensimagcafet-network:
    name: EnsimagCafet-Network
    driver: bridge

volumes:
  postgres-data:
    name: EnsimagCafet-PostgresData-Volume
    driver: local
  antiforgery-keys-data:
    name: EnsimagCafet-AntiforgeryKeysData-Volume
    driver: local

services:
  whoami:
    image: traefik/whoami
    container_name: WhoAmI
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.cafet-ensimag.fr`)
      - traefik.http.routers.whoami.entrypoints=web

  ensimagcafet.web:
    container_name: EnsimagCafet.Web
    image: ${DOCKER_REGISTRY-}ensimagcafetweb
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.Web/Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet-network
    volumes:
      - antiforgery-keys-data:/var/af-keys
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.cafetensimag.rule=Host(`whoami.cafet-ensimag.fr`)"
      #- "traefik.http.routers.cafetensimag.entrypoints=web"

  ensimagcafet.entityframeworkcore.dbmigrator:
    container_name: EnsimagCafet.EntityFrameworkCore.DbMigrator
    image: ${DOCKER_REGISTRY-}ensimagcafetentityframeworkcoredbmigrator
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.EntityFrameworkCore.DbMigrator/Dockerfile
    environment:
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet-network

  postgres:
    container_name: Postgres
    image: postgres
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: ensimagcafetdev
      POSTGRES_PASSWORD: EnsimagCafetDev
      POSTGRES_DB: ensimagcafetdev
    networks:
      - ensimagcafet-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  traefik:
    container_name: Traefik
    image: traefik
    restart: always
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro