version: '3.9'

name: ensimagcafet

networks:
  ensimagcafet.web-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  antiforgery-keys-data:
    driver: local

services:
  ensimagcafet.web:
    container_name: EnsimagCafet.Web
    image: ${DOCKER_REGISTRY-}ensimagcafetweb
    depends_on:
    - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.Web/Dockerfile
    restart: always
    ports:
    - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet.web-network
    volumes:
    - antiforgery-keys-data:/var/af-keys

  ensimagcafet.entityframeworkcore.dbmigrator:
    container_name: EnsimagCafet.EntityFrameworkCore.DbMigrator
    image: ${DOCKER_REGISTRY-}ensimagcafetentityframeworkcoredbmigrator
    depends_on:
    - "postgres"
    build:
      context: .
      dockerfile: EnsimagCafet.EntityFrameworkCore.DbMigrator/Dockerfile
    environment:
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet.web-network

  postgres:
    container_name: Postgres
    image: postgres
    expose:
    - 5432
    restart: always
    environment:
      POSTGRES_USER: ensimagcafetdev
      POSTGRES_PASSWORD: EnsimagCafetDev
      POSTGRES_DB: ensimagcafetdev
    networks:
      - ensimagcafet.web-network
    volumes:
    - postgres-data:/var/lib/postgresql/data