version: '3.9'

name: ensimagcafet

networks:
  ensimagcafet.web-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  antiforgery-keys-data:
    driver: local

services:
  ensimagcafet.web:
    container_name: EnsimagCafet.Web
    image: ${DOCKER_REGISTRY-}ensimagcafetweb
    depends_on:
    - postgres
    build:
      context: .
      dockerfile: EnsimagCafet.Web/Dockerfile
    restart: always
    ports:
    - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet.web-network
    volumes:
    - antiforgery-keys-data:/var/af-keys
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.ensimagcafetweb.rule=Host(`localhost`)"
    - "traefik.http.routers.ensimagcafetweb.entrypoints=web"

  ensimagcafet.entityframeworkcore.dbmigrator:
    container_name: EnsimagCafet.EntityFrameworkCore.DbMigrator
    image: ${DOCKER_REGISTRY-}ensimagcafetentityframeworkcoredbmigrator
    depends_on:
    - "postgres"
    build:
      context: .
      dockerfile: EnsimagCafet.EntityFrameworkCore.DbMigrator/Dockerfile
    environment:
      DB_CONNECTION_STRING: host=postgres;port=5432;database=ensimagcafetdev;username=ensimagcafetdev;password=EnsimagCafetDev
    networks:
      - ensimagcafet.web-network

  postgres:
    container_name: Postgres
    image: postgres
    expose:
    - 5432
    restart: always
    environment:
      POSTGRES_USER: ensimagcafetdev
      POSTGRES_PASSWORD: EnsimagCafetDev
      POSTGRES_DB: ensimagcafetdev
    networks:
      - ensimagcafet.web-network
    volumes:
    - postgres-data:/var/lib/postgresql/data

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=contact@cafet-ensimag.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`cafet-ensimag.fr`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
